#include "HTMLWriter.h"
#include <fstream>
using namespace std;

HTMLWriter::HTMLWriter(const string& fileName, const string& content)
	:DocWriter(fileName, content){
	_fontName = "±¼¸²";
	_fontSize = 3;
	_fontColor = "black";
}

HTMLWriter::~HTMLWriter(){}

void HTMLWriter::Write(){
	ofstream of(_fileName.c_str() );

	of << "<HTML><HEAD><TITLE>This document was generated by HTMLWriter</TITLE></HEAD><BODY>";
	of << "<H1>Content</H1>";

	of << "<Font name = '" << _fontName << "' size = '" << _fontSize << "' color = '" << _fontColor << "'>";

	of << _content;
	of << "</FONT>";
	of << "</BODY></HTML>";
}

void HTMLWriter::SetFont(const string& fontName, int fontSize, const string& fontColor){
	_fontName = fontName;
	_fontSize = fontSize;
	_fontColor = fontColor;
}